"""
Architecture diagram for the EEP Next.js Template.

Generates: architecture.png

Run with:
    uv run python main.py

Icons:
    icons/folder-*.png  — generated by this script on first run via Pillow
    Real logos used for external services (React, Next.js, Vercel, Postgres, Docker, Clerk)
"""

import os

from diagrams import Cluster, Diagram, Edge
from diagrams.custom import Custom
from diagrams.onprem.client import Users
from diagrams.onprem.container import Docker
from diagrams.programming.framework import NextJs, React, Vercel


def _ensure_icons() -> None:
    """Generate folder + badge icons if they don't already exist."""
    os.makedirs("icons", exist_ok=True)
    if os.path.exists("icons/folder-blue.png"):
        return

    from PIL import Image, ImageDraw, ImageFont  # noqa: PLC0415

    def folder(path: str, color: tuple[int, int, int]) -> None:
        size = 256
        img = Image.new("RGBA", (size, size), (0, 0, 0, 0))
        d = ImageDraw.Draw(img)
        s = size
        d.rounded_rectangle(
            [s * 0.05, s * 0.28, s * 0.95, s * 0.85],
            radius=s * 0.07,
            fill=color,
        )
        d.rounded_rectangle(
            [s * 0.05, s * 0.18, s * 0.45, s * 0.35],
            radius=s * 0.05,
            fill=color,
        )
        img.save(path)

    folder("icons/folder-blue.png", (59, 130, 246))
    folder("icons/folder-purple.png", (124, 58, 237))
    folder("icons/folder-green.png", (22, 163, 74))
    folder("icons/folder-amber.png", (217, 119, 6))
    folder("icons/folder-gray.png", (107, 114, 128))


_ensure_icons()

# Resolve absolute icon paths so the diagram works from any cwd.
_here = os.path.dirname(os.path.abspath(__file__))


def icon(name: str) -> str:
    """Resolve a Material Icon Theme PNG by folder name."""
    return os.path.join(_here, "icons", "material-png", f"{name}.png")


graph_attr = {
    "fontsize": "18",
    "bgcolor": "white",
    "pad": "1.0",
    "splines": "ortho",
    "nodesep": "0.6",
    "ranksep": "0.9",
}

with Diagram(
    "EEP Next.js Template — Architecture",
    filename="architecture",
    show=False,
    direction="LR",
    graph_attr=graph_attr,
):
    user = Users("Browser\n/ Client")

    with Cluster("Vercel  (production host)"):
        vercel = Vercel("Vercel Edge\nSSR + CDN")

    with Cluster("Clerk  (Auth SaaS)"):
        clerk = Custom("Clerk\nAuth + Sessions", icon("clerk"))

    with Cluster("EEP Next.js App  ─  src/"):
        ts_badge = Custom("TypeScript", icon("typescript"))

        with Cluster("Client Layer\ncomponents/  hooks/  store/"):
            react    = React("React 19\ncomponents/")
            zustand  = Custom("Zustand Store\nstore/",   icon("folder-store"))
            swr_hook = Custom("SWR Hooks\nhooks/",       icon("folder-hook"))

        with Cluster("API Layer\napp/api/  actions/"):
            routes  = NextJs("Route Handlers\napp/api/")
            actions = Custom("Server Actions\nactions/", icon("folder-controller"))

        with Cluster("Server Layer\nclasses/"):
            services = Custom("Services\nclasses/services/", icon("folder-server"))
            loggers  = Custom("Loggers\nclasses/loggers/",   icon("folder-log"))
            errors   = Custom("Error Types\nclasses/errors/", icon("folder-class"))

        with Cluster("Validation\nvalidation/"):
            zod = Custom("Zod Schemas\nvalidation/", icon("folder-guard"))

    with Cluster("Data"):
        postgres = Custom("Neon\n(prod)", icon("neon"))
        docker   = Docker("docker-compose\n(local dev)")

    with Cluster("Docs Site  ─  docs/"):
        fumadocs = NextJs("Fumadocs\nlocalhost:3001")

    # ── Request flow ──────────────────────────────────────────────
    user    >> Edge(label="HTTPS")      >> vercel
    vercel  >> Edge(label="SSR / API")  >> react
    vercel  >> Edge(label="session\ngate", style="dashed") >> clerk

    # Auth claims back to API layer
    clerk >> Edge(label="JWT claims", style="dashed", color="gray") >> routes

    # Client internals
    react >> swr_hook
    react >> zustand

    # SWR → route handlers
    swr_hook >> Edge(label="fetch") >> routes

    # Server actions
    react >> Edge(label="form\nsubmit") >> actions

    # API + actions → services
    routes  >> Edge(label="delegate") >> services
    actions >> Edge(label="delegate") >> services

    # Validation shared surface
    zod >> Edge(style="dashed", color="gray") >> routes
    zod >> Edge(style="dashed", color="gray") >> actions

    # Services → DB
    services >> Edge(label="Drizzle ORM") >> postgres

    # Logging (cross-cutting, dotted)
    loggers >> Edge(style="dotted", color="lightgray") >> services
    loggers >> Edge(style="dotted", color="lightgray") >> routes

    # Local DB container
    docker >> Edge(style="dashed", color="lightgray", label="runs") >> postgres

    # Docs — separate process
    user >> Edge(label=":3001", style="dashed", color="lightgray") >> fumadocs
